DB_URL = "postgresql://postgres.ttptxdlvqwkitmbuafxn:Itagesso2026@aws-1-us-west-2.pooler.supabase.com:6543/postgres"

SUPABASE_URL = "https://ttptxdlvqwkitmbuafxn.supabase.co"

SUPABASE_KEY = "sb_publishable_W6g9Xhu7jJLDdPlGQeZqIw_8CPUIjAT"
